<script>
// @ts-nocheck

import { Form, FormGroup, Input, Label, Button, Alert } from "sveltestrap";  
import { goto } from '$app/navigation';

function usernameValidation(value) {
    const bannedWords = ['a55',
        'a55hole',
        'aeolus',
        'ahole',
        'anal',
        'analprobe',
        'anilingus',
        'anus',
        'areola',
        'areole',
        'arian',
        'aryan',
        'ass',
        'assbang',
        'assbanged',
        'assbangs',
        'asses',
        'assfuck',
        'assfucker',
        'assh0le',
        'asshat',
        'assho1e',
        'ass hole',
        'assholes',
        'assmaster',
        'assmunch',
        'asswipe',
        'asswipes',
        'azazel',
        'azz',
        'b1tch',
        'ballsack',
        'bang',
        'bastard',
        'bastards',
        'bawdy',
        'beaner',
        'beardedclam',
        'beastiality',
        'beatch',
        'beater',
        'beeyotch',
        'beotch',
        'biatch',
        'bigtits',
        'big tits',
        'bimbo',
        'bitch',
        'bitched',
        'bitches',
        'bitchy',
        'blow job',
        'blowjob',
        'blowjobs',
        'boned',
        'boner',
        'boners',
        'bong',
        'boob',
        'boobies',
        'boobs',
        'booby',
        'booger',
        'bookie',
        'bootee',
        'bootie',
        'booty',
        'booze',
        'boozer',
        'boozy',
        'bosom',
        'bosomy',
        'bowels',
        'bra',
        'brassiere',
        'breast',
        'breasts',
        'bugger',
        'bukkake',
        'bullshit',
        'bull shit',
        'bullshits',
        'bullshitted',
        'bullturds',
        'bung',
        'busty',
        'butt',
        'butt fuck',
        'buttfuck',
        'buttfucker',
        'buttfucker',
        'buttplug',
        'c.0.c.k',
        'c.o.c.k.',
        'c.u.n.t',
        'c0ck',
        'c-0-c-k',
        'caca',
        'cahone',
        'cameltoe',
        'carpetmuncher',
        'cawk',
        'cervix',
        'chinc',
        'chincs',
        'chink',
        'chink',
        'chode',
        'chodes',
        'cl1t',
        'climax',
        'clit',
        'clitoris',
        'clitorus',
        'clits',
        'clitty',
        'cocain',
        'cocaine',
        'cock',
        'c-o-c-k',
        'cockblock',
        'cockholster',
        'cockknocker',
        'cocks',
        'cocksmoker',
        'cocksucker',
        'cock sucker',
        'coital',
        'commie',
        'condom',
        'coon',
        'coons',
        'corksucker',
        'crabs',
        'crack',
        'cracker',
        'crackwhore',
        'crap',
        'crappy',
        'cum',
        'cummin',
        'cumming',
        'cumshot',
        'cumshots',
        'cumslut',
        'cumstain',
        'cunilingus',
        'cunnilingus',
        'cunny',
        'cunt',
        'cunt',
        'c-u-n-t',
        'cuntface',
        'cunthunter',
        'cuntlick',
        'cuntlicker',
        'cunts',
        'd0ng',
        'd0uch3',
        'd0uche',
        'd1ck',
        'd1ld0',
        'd1ldo',
        'dago',
        'dagos',
        'dawgie-style',
        'dick',
        'dickbag',
        'dickdipper',
        'dickface',
        'dickflipper',
        'dickhead',
        'dickheads',
        'dickish',
        'dick-ish',
        'dickripper',
        'dicksipper',
        'dickweed',
        'dickwhipper',
        'dickzipper',
        'diddle',
        'dike',
        'dildo',
        'dildos',
        'diligaf',
        'dillweed',
        'dimwit',
        'dingle',
        'dipship',
        'doggie-style',
        'doggy-style',
        'dong',
        'doofus',
        'doosh',
        'dopey',
        'douch3',
        'douche',
        'douchebag',
        'douchebags',
        'douchey',
        'drunk',
        'dumass',
        'dumbass',
        'dumbasses',
        'dummy',
        'dyke',
        'dykes',
        'ejaculate',
        'enlargement',
        'erect',
        'erection',
        'erotic',
        'essohbee',
        'extacy',
        'extasy',
        'f.u.c.k',
        'fack',
        'fag',
        'fagg',
        'fagged',
        'faggit',
        'faggot',
        'fagot',
        'fags',
        'faig',
        'faigt',
        'fannybandit',
        'fart',
        'fartknocker',
        'fat',
        'felch',
        'felcher',
        'felching',
        'fellate',
        'fellatio',
        'feltch',
        'feltcher',
        'fisted',
        'fisting',
        'fisty',
        'floozy',
        'foad',
        'fondle',
        'foobar',
        'foreskin',
        'freex',
        'frigg',
        'frigga',
        'fubar',
        'fuck',
        'f-u-c-k',
        'fuckass',
        'fucked',
        'fucked',
        'fucker',
        'fuckface',
        'fuckin',
        'fucking',
        'fucknugget',
        'fucknut',
        'fuckoff',
        'fucks',
        'fucktard',
        'fuck-tard',
        'fuckup',
        'fuckwad',
        'fuckwit',
        'fudgepacker',
        'fuk',
        'fvck',
        'fxck',
        'gae',
        'gai',
        'ganja',
        'gay',
        'gays',
        'gey',
        'gfy',
        'ghay',
        'ghey',
        'gigolo',
        'glans',
        'goatse',
        'godamn',
        'godamnit',
        'goddam',
        'goddammit',
        'goddamn',
        'goldenshower',
        'gonad',
        'gonads',
        'gook',
        'gooks',
        'gringo',
        'gspot',
        'g-spot',
        'gtfo',
        'guido',
        'h0m0',
        'h0mo',
        'handjob',
        'hard on',
        'hebe',
        'heeb',
        'heroin',
        'herp',
        'herpes',
        'herpy',
        'hitler',
        'hiv',
        'hobag',
        'hom0',
        'homey',
        'homo',
        'homoey',
        'honky',
        'hooch',
        'hookah',
        'hooker',
        'hoor',
        'hootch',
        'hooter',
        'hooters',
        'horny',
        'hump',
        'humped',
        'humping',
        'hussy',
        'hymen',
        'inbred',
        'incest',
        'injun',
        'j3rk0ff',
        'jackass',
        'jackhole',
        'jackoff',
        'jap',
        'japs',
        'jerk',
        'jerk0ff',
        'jerked',
        'jerkoff',
        'jism',
        'jiz',
        'jizm',
        'jizz',
        'jizzed',
        'junkie',
        'junky',
        'kike',
        'kikes',
        'kkk',
        'klan',
        'knobend',
        'kooch',
        'kooches',
        'kootch',
        'kraut',
        'kyke',
        'labia',
        'lech',
        'leper',
        'lesbians',
        'lesbo',
        'lesbos',
        'lez',
        'lezbian',
        'lezbians',
        'lezbo',
        'lezbos',
        'lezzie',
        'lezzies',
        'lezzy',
        'lmao',
        'lmfao',
        'loin',
        'loins',
        'lube',
        'lusty',
        'mams',
        'massa',
        'masterbate',
        'masterbating',
        'masterbation',
        'masturbate',
        'masturbating',
        'masturbation',
        'maxi',
        'menses',
        'menstruate',
        'menstruation',
        'meth',
        'm-fucking',
        'mofo',
        'molest',
        'moolie',
        'moron',
        'motherfucka',
        'motherfucker',
        'motherfucking',
        'mtherfucker',
        'mthrfucker',
        'mthrfucking',
        'muff',
        'muffdiver',
        'murder',
        'muthafuckaz',
        'muthafucker',
        'mutherfucker',
        'mutherfucking',
        'muthrfucking',
        'nad',
        'nads',
        'naked',
        'napalm',
        'nappy',
        'nazi',
        'nazism',
        'negro',
        'nigga',
        'niggah',
        'niggas',
        'niggaz',
        'nigger',
        'nigger',
        'niggers',
        'niggle',
        'niglet',
        'nimrod',
        'ninny',
        'nipple',
        'nooky',
        'nympho',
        'opiate',
        'opium',
        'oral',
        'orally',
        'organ',
        'orgasm',
        'orgasmic',
        'orgies',
        'orgy',
        'ovary',
        'ovum',
        'ovums',
        'p.u.s.s.y.',
        'paddy',
        'paki',
        'pantie',
        'panties',
        'panty',
        'pastie',
        'pasty',
        'pcp',
        'pecker',
        'pedo',
        'pedophile',
        'pedophilia',
        'pedophiliac',
        'pee',
        'peepee',
        'penetrate',
        'penetration',
        'penial',
        'penile',
        'penis',
        'perversion',
        'peyote',
        'phalli',
        'phallic',
        'phuck',
        'pillowbiter',
        'pimp',
        'pinko',
        'piss',
        'pissed',
        'pissoff',
        'piss-off',
        'pms',
        'polack',
        'pollock',
        'poon',
        'poontang',
        'porn',
        'porno',
        'pornography',
        'pot',
        'potty',
        'prick',
        'prig',
        'prostitute',
        'prude',
        'pube',
        'pubic',
        'pubis',
        'punkass',
        'punky',
        'puss',
        'pussies',
        'pussy',
        'pussypounder',
        'puto',
        'queaf',
        'queef',
        'queef',
        'queer',
        'queero',
        'queers',
        'quicky',
        'quim',
        'racy',
        'rape',
        'raped',
        'raper',
        'rapist',
        'raunch',
        'rectal',
        'rectum',
        'rectus',
        'reefer',
        'reetard',
        'reich',
        'retard',
        'retarded',
        'revue',
        'rimjob',
        'ritard',
        'rtard',
        'r-tard',
        'rum',
        'rump',
        'rumprammer',
        'ruski',
        's.h.i.t.',
        's.o.b.',
        's0b',
        'sadism',
        'sadist',
        'scag',
        'scantily',
        'schizo',
        'schlong',
        'screw',
        'screwed',
        'scrog',
        'scrot',
        'scrote',
        'scrotum',
        'scrud',
        'scum',
        'seaman',
        'seamen',
        'seduce',
        'semen',
        'sex',
        'sexual',
        'sh1t',
        's-h-1-t',
        'shamedame',
        'shit',
        's-h-i-t',
        'shite',
        'shiteater',
        'shitface',
        'shithead',
        'shithole',
        'shithouse',
        'shits',
        'shitt',
        'shitted',
        'shitter',
        'shitty',
        'shiz',
        'sissy',
        'skag',
        'skank',
        'slave',
        'sleaze',
        'sleazy',
        'slut',
        'slutdumper',
        'slutkiss',
        'sluts',
        'smegma',
        'smut',
        'smutty',
        'snatch',
        'sniper',
        'snuff',
        's-o-b',
        'sodom',
        'souse',
        'soused',
        'sperm',
        'spic',
        'spick',
        'spik',
        'spiks',
        'spooge',
        'spunk',
        'steamy',
        'stfu',
        'stiffy',
        'stoned',
        'strip',
        'stroke',
        'sumofabiatch',
        't1t',
        'tampon',
        'tard',
        'tawdry',
        'teabagging',
        'teat',
        'terd',
        'teste',
        'testee',
        'testes',
        'testicle',
        'testis',
        'thrust',
        'thug',
        'tinkle',
        'tit',
        'titfuck',
        'titi',
        'tits',
        'tittiefucker',
        'titties',
        'titty',
        'tittyfuck',
        'tittyfucker',
        'toke',
        'toots',
        'tramp',
        'transsexual',
        'trashy',
        'tubgirl',
        'turd',
        'tush',
        'twat',
        'twats',
        'ugly',
        'undies',
        'unwed',
        'urinal',
        'urine',
        'uterus',
        'uzi',
        'vag',
        'vagina',
        'valium',
        'viagra',
        'virgin',
        'vixen',
        'vodka',
        'vomit',
        'voyeur',
        'vulgar',
        'vulva',
        'wad',
        'wang',
        'wank',
        'wanker',
        'wazoo',
        'wedgie',
        'weed',
        'weenie',
        'weewee',
        'weiner',
        'weirdo',
        'wench',
        'wetback',
        'wh0re',
        'wh0reface',
        'whitey',
        'whiz',
        'whoralicious',
        'whore',
        'whorealicious',
        'whored',
        'whoreface',
        'whorehopper',
        'whorehouse',
        'whores',
        'whoring',
        'wigger',
        'womb',
        'woody',
        'yeasty',
        'yobbo',
        'zoophile'];
    return (bannedWords.some((word) => (value.indexOf(word) !== -1)) ||
    value.length < 4 ||
    value.length > 15 ||
    value.indexOf(" ") > -1);
}

function emailValidation(value) {
    const regex = /(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/
    return !(regex.test(value));
}

function passValidation(value) {
    return value.length < 8;
}

function sleep(ms) {
        return new Promise((resolve) => setTimeout(resolve, ms)); // resolve is a callback function
    }

async function submit() {
    const res = await fetch('http://localhost:3333/auth/register/confirm', {
        method: 'POST',
        headers: {
            'Content-Type':'application/json'
        },
        body: JSON.stringify({
            username: username,
            email: email,
            password: password
        })
    });
    if (res.status === 406) {
        statusHeader = 'Registration Error'
        statusColor = 'danger'
        statusMessage = 'It looks like your username or email has already been taken.'
    } else {
        statusHeader = 'Success!'
        statusColor = 'success'
        statusMessage = "Success! You can now login."
        statusReturned = true;
        sleep(3000);
        goto('/auth/login');
    }
}


let username = '';
let email = '';
let password = '';

let statusReturned = false;
let statusHeader = 'Reminder:';
let statusMessage = 'You may only have ONE account. Violating this rule will result in ALL associated accounts being banned.';
let statusColor = 'warning';
</script>
    
    
<main> 
    <div class='wrapper wrapper--navbar'>
    </div>
    <div class='wrapper wrapper--register'>
    <Form>
        <FormGroup>
            <Label class='input' for="exampleUsername">Username</Label>
            <Input
              type="text"
              name="username"
              bind:value = {username}
              id="exampleUsername"			
              placeholder="Enter username"/>
            {#if usernameValidation(username)}
                <div class='p-2 error-registration-username'>
                
                    Your username must:
                    <ul>
                        <li>Have between 4 and 15 characters.</li>
                        <li>Not contain profanity or spaces.</li>
                        <li>Be unique.</li>
                    </ul>
                </div>
            {/if}
        </FormGroup>


            <FormGroup>
                <Label for="exampleEmail">Email</Label>
                <Input
                  type="email"
                  name="email"
                  bind:value={email}
                  id="exampleEmail"
                  placeholder="Enter email"
                />
            {#if emailValidation(email)}
            <div class='p-2 wrapper--registerValidation'>
                <div class='p-2 error-registration-email'>
                    Your email must be valid and unique.
                </div>
            </div>
            {/if}
              </FormGroup>
              <FormGroup>
                <Label for="examplePassword">Password</Label>
                <Input
                  type="password"
                  name="password"
                  bind:value={password}
                  id="examplePassword"
                  placeholder="Enter password"
                />
            {#if passValidation(password)}
            <div class='p-2 wrapper--registerValidation'>
                <div class='p-2 error-registration-pass'>
                    Your password must contain at least 8 characters.
                </div>
            </div>
            {/if}
              </FormGroup>
        </Form>
    </div>
    {#if (!usernameValidation(username) && !emailValidation(email) && !passValidation(password) && !statusReturned)}
    <Button color='info' on:click={submit}>
        Submit
    </Button>
    {/if}
    <div class='wrapper wrapper--login-status'>
        <Alert 
        color={statusColor} class='login-status'>
            <h4 class='header--login-status'>{statusHeader}</h4>
            {statusMessage}
        {#if !statusReturned}
            <a class='alert-link' href='/auth/register'>Register Here</a>
        {/if}
        </Alert>
    </div>




<style>
    .html {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    }
    .wrapper--
    .error-registration--username {
        border: 2px dotted red;
        width: 35%;
        padding: 11px;
    }
    .error-registration--email {
        border: 2px dotted red;
        width: 35%;
        padding: 11px;
    }
    .error-registration--pass {
        border: 2px dotted red;
        width: 35%;
        padding: 11px;
    }

    .wrapper--login-status {
        padding: 15px 7px;
        vertical-align: middle;
    }
</style>
</main> 